'''
Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.
'''
s_pre = 1
s_next = 2
sum = 2
while s_pre < 4000000:
    s = s_pre + s_next
    s_pre = s_next
    s_next = s
#     print(s)
    if s%2 == 0:
        sum += s
print(sum)
    